upstream crystal-china.org {
    server 127.0.0.1:5000;
}

server {
    server_name crystal-china.org;

    listen 80 default_server;
    listen [::]:80 default_server;

    location ~ \.(aspx|php|jsp|cgi|py|html|env(\..*)?|(aws|docker|git|github|gitlab|ssh|svn|well-known)(/.*)?|DS_Store|ya?ml|backup|bak|local|prod|production|less|save|sample|properties|log|old|lock|md)$|/(phpinfo|actuator|wp-content|wp-includes|static|public|gateway\;) {
        return 410;
    }

    # nginx 默认值是 1M, 如果不上传图片，肯定是够大的。
    client_max_body_size 5M;

    root /home/pi/apps/crystal_china_production/public;

    location / {
        include includes/proxy.conf;
        proxy_pass http://crystal-china.org;
    }

    location ~ ^/(assets|packs) {
        include includes/assets.conf;
    }
}

 server {
     server_name assets.crystal-china.org;
     root /home/pi/apps/crystal_china_production/public;

     include includes/assets.conf;
 }

# server {
#     server_name upload.crystal-china.org;
#     root /home/crystal_china/apps/patchy/data;
#     ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
#     ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

#     include includes/ssl.conf;
#     include includes/assets.conf;
# }

# server {
#     server_name me.crystal-china.org;
#     ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
#     ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

#     include includes/ssl.conf;
#     include includes/assets.conf;

#     client_max_body_size 20M;

#     location / {
#         include includes/proxy.conf;
#         proxy_pass http://127.0.0.1:8080;
#     }
# }
