upstream crystal-china.org {
    server 127.0.0.1:5000;
}

server {
    server_name crystal-china.org;

    listen 80 default_server;
    listen [::]:80 default_server;

    return 301 https://$host$request_uri;
}

server {
    server_name crystal-china.org;

    location ~ \.(aspx|php|jsp|cgi)$ {
        return 410;
    }

    # nginx 默认值是 1M, 如果不上传图片，肯定是够大的。
    client_max_body_size 5M;

    root /home/crystal_china/apps/website_production/dist;
    ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

    include includes/ssl.conf;
    # include includes/brotli.conf;

    # location /videos/upload {
    #     # 强制 Nginx 忽略 server 块继承的 root 指令
    #     # 只要这个 location 块中有 alias 或 root，就不会查找 server 块的 root
    #     # alias /dev/null;
    #     # proxy_pass 指令设置反向代理的目标地址
    #     # 注意末尾的斜杠 / 的用法：
    #     # - 如果目标地址 (127.0.0.1:8080/) 末尾有斜杠：
    #     #   Nginx 会将匹配到的路径部分 (/puppies) 移除，并将剩余部分附加到目标地址。
    #     #   例如：访问 crystal-china.org/puppies/about -> 代理到 127.0.0.1:8080/about
    #     #   访问 crystal-china.org/puppies -> 代理到 127.0.0.1:8080/
    #     # - 如果目标地址 (127.0.0.1:8080) 末尾**没有**斜杠：
    #     #   Nginx 会将完整的 URI (/puppies/...) 附加到目标地址。
    #     #   例如：访问 crystal-china.org/puppies/about -> 代理到 127.0.0.1:8080/puppies/about
    #     include includes/proxy.conf;
    #     proxy_pass http://127.0.0.1:8080/;
    # }


    location / {
        include includes/proxy.conf;
        proxy_pass http://crystal-china.org;
    }

    location ~ ^/(assets|packs) {
        include includes/assets.conf;
    }
}

server {
    server_name assets.crystal-china.org;
    root /home/crystal_china/apps/website_production/dist;
    ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

    include includes/ssl.conf;
    include includes/assets.conf;
}

server {
    server_name upload.crystal-china.org;
    root /home/crystal_china/apps/patchy/data;
    ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

    include includes/ssl.conf;
    include includes/assets.conf;
}

server {
    server_name me.crystal-china.org;
    ssl_certificate /etc/ssl/crystal-china.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/crystal-china.org/privkey.pem;

    include includes/ssl.conf;
    include includes/assets.conf;

    client_max_body_size 20M;

    location / {
        include includes/proxy.conf;
        proxy_pass http://127.0.0.1:8080;
    }
}
