en:
  avram:
    attribute_variants:
      actor_id: "Actor"
      avatar: "Avatar"
      available: "Available"
      captcha_code: "Captcha code"
      changed_column_name: "Changed field"
      color: "Color"
      comment: "Comment"
      comment_id: "Comment"
      comment_thread_id: "Comment thread"
      content: "Content"
      date: "Date"
      doc_id: "Document"
      email: "Email"
      from: "Previous value"
      hour: "Hour"
      language: "Language"
      kind: "Notification type"
      name: "Name"
      node_id: "Node"
      parent_id: "Parent comment"
      password: "Password"
      password_confirmation: "Password confirmation"
      position: "Position"
      read_at: "Read at"
      slug: "Slug"
      summary: "Summary"
      target: "Notification target"
      title: "Title"
      to: "New value"
      topic_id: "Topic"
      user_id: "User"
      vote_counts: "Vote counts"
      vote_type: "Vote type"
    validate_acceptance_of: "must be accepted"
    validate_at_most_one_filled: "must be blank"
    validate_confirmation_of: "must match"
    validate_exact_size_of: "must be exactly %{size} characters long"
    validate_exactly_one_filled: "at least one must be filled"
    validate_format_of: "is invalid"
    validate_inclusion_of: "is not included in the list"
    validate_max_size_of: "must not have more than %{size} characters"
    validate_min_size_of: "must have at least %{size} characters"
    validate_numeric_max: "must be less than %{size}"
    validate_numeric_min: "must be greater than %{size}"
    validate_numeric_nil: "must not be nil"
    validate_required: "is required"
    validate_uniqueness_of: "is already taken"
