zh-CN:
  avram:
    attribute_variants:
      actor_id: "操作用户"
      avatar: "头像"
      available: "是否可用"
      captcha_code: "人机验证码"
      changed_column_name: "变更字段"
      color: "颜色"
      comment: "备注"
      comment_id: "评论"
      comment_thread_id: "评论区"
      content: "正文"
      date: "日期"
      doc_id: "文档"
      email: "电子邮件"
      from: "原值"
      hour: "时段"
      language: "语言"
      kind: "通知类型"
      name: "昵称"
      node_id: "节点"
      parent_id: "父评论"
      password: "密码"
      password_confirmation: "确认密码"
      position: "排序位置"
      read_at: "阅读时间"
      slug: "路径标识"
      summary: "简介"
      target: "通知目标"
      title: "标题"
      to: "新值"
      topic_id: "主题"
      user_id: "用户"
      vote_counts: "投票统计"
      vote_type: "投票类型"
    validate_acceptance_of: "must be accepted"
    validate_at_most_one_filled: "must be blank"
    validate_confirmation_of: "必须匹配"
    validate_exact_size_of: "长度必须为 %{size} 个字符"
    validate_exactly_one_filled: "at least one must be filled"
    validate_format_of: "is invalid"
    validate_inclusion_of: "is not included in the list"
    validate_max_size_of: "must not have more than %{size} characters"
    validate_min_size_of: "must have at least %{size} characters"
    validate_numeric_max: "must be less than %{size}"
    validate_numeric_min: "must be greater than %{size}"
    validate_numeric_nil: "数字不可以为空"
    validate_required: "需要的"
    validate_uniqueness_of: "已经存在了"
