class CommentThread < BaseModel
  table do
    belongs_to doc : Doc?
    belongs_to topic : Topic?
    has_many comments : Comment

    polymorphic target, associations: [:doc, :topic]
    column floor_counter : Int32, autogenerated: true
  end
end
