class Comment < BaseModel
  struct Preferences
    include JSON::Serializable

    property? path_for_doc : String?
  end

  struct VoteCounts
    include JSON::Serializable

    property 👍 : Int32 = 0
    property 👎 : Int32 = 0
    property 😄 : Int32 = 0
    property ❤️ : Int32 = 0
    property 🎉 : Int32 = 0
    property 😕 : Int32 = 0
    property 👀️ : Int32 = 0
  end

  table do
    belongs_to comment_thread : CommentThread
    belongs_to doc : Doc?
    belongs_to parent : Comment?
    belongs_to root : Comment?
    belongs_to user : User
    has_many votes : Vote

    column content : String
    column floor : Int32, autogenerated: true
    column floor_counter : Int32, autogenerated: true
    column descendants_count : Int32, autogenerated: true
    column children_count : Int32, autogenerated: true

    column preferences : Comment::Preferences, serialize: true
    column vote_counts : Comment::VoteCounts, serialize: true
  end
end
