class Doc < BaseModel
  struct VoteCounts
    include JSON::Serializable

    property 👍 : Int32 = 0
    property 👎 : Int32 = 0
    property ❤️ : Int32 = 0
  end

  table do
    column path_index : String
    column view_count : Int32, autogenerated: true
    column reply_floor_counter : Int32, autogenerated: true

    has_many replies : Reply
    has_many votes : Vote

    column vote_counts : Doc::VoteCounts, serialize: true, autogenerated: true
  end
end
