class Reply < BaseModel
  struct Preferences
    include JSON::Serializable

    property? path_for_doc : String?
  end

  struct Votes
    include JSON::Serializable

    property 👍 : Int32 = 0
    property 👎 : Int32 = 0
    property 😄 : Int32 = 0
    property ❤️ : Int32 = 0
    property 🎉 : Int32 = 0
    property 😕 : Int32 = 0
    property 👀️ : Int32 = 0
  end

  table do
    belongs_to doc : Doc?
    belongs_to reply : Reply?
    belongs_to root_reply : Reply?
    belongs_to user : User

    column content : String
    column user_name : String
    column user_avatar : String?
    column floor : Int32, autogenerated: true
    column reply_floor_counter : Int32, autogenerated: true
    column thread_replies_count : Int32, autogenerated: true
    column direct_replies_count : Int32, autogenerated: true

    polymorphic target, associations: [:doc, :reply]
    column preferences : Reply::Preferences, serialize: true
    column votes : Reply::Votes, serialize: true
  end
end
