class Topic < BaseModel
  include Avram::SoftDelete::Model

  table do
    belongs_to user : User
    belongs_to node : Node
    belongs_to last_reply_user : User?
    has_one comment_thread : CommentThread?

    column title : String
    column content : String
    column edited_at : Time?
    column soft_deleted_at : Time?
    column replies_count : Int32, autogenerated: true
    column last_active_at : Time, autogenerated: true
  end
end
